#!/usr/bin/env bash
# Bootstrap the Stream Deck configuration on macOS.
#
# - Verifies the Stream Deck app (and optionally the @elgato/cli) are present.
# - Builds the TypeScript glue commands and links the executables into
#   ~/.local/bin as `sd-<name>`.
# - Creates a git-ignored secrets template at ~/.config/streamdeck/secrets.env.
# - Prints the plugin install checklist.
#
# Safe to re-run (idempotent).

set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DIR/.." && pwd)"

BIN_DIR="$HOME/.local/bin"
CFG_DIR="$HOME/.config/streamdeck"
SECRETS="$CFG_DIR/secrets.env"

info()  { printf '\033[1;34m•\033[0m %s\n' "$*"; }
ok()    { printf '\033[1;32m✓\033[0m %s\n' "$*"; }
warn()  { printf '\033[1;33m!\033[0m %s\n' "$*"; }

echo "Stream Deck bootstrap"
echo "====================="

# 1. App check
if [[ -d "/Applications/Elgato Stream Deck.app" ]]; then
  ok "Stream Deck app found"
else
  warn "Stream Deck app not found. Install: brew install --cask elgato-stream-deck"
fi

# 2. Toolchain check (pnpm builds the plugins + scripts)
if command -v pnpm >/dev/null 2>&1; then
  ok "pnpm present ($(pnpm --version 2>/dev/null || echo '?'))"
else
  warn "pnpm not found — install with: corepack enable && corepack prepare pnpm@10.15.0 --activate"
fi
if command -v icalBuddy >/dev/null 2>&1; then
  ok "icalBuddy present (local calendar for the Next Meeting + MTGS keys)"
else
  warn "icalBuddy not found — the calendar keys need it: brew install ical-buddy"
fi
if command -v streamdeck >/dev/null 2>&1; then
  ok "@elgato/cli present ($(streamdeck --version 2>/dev/null || echo '?'))"
else
  info "@elgato/cli not installed (only needed to build custom plugins): pnpm add -g @elgato/cli"
fi

# 3. Build + link the TypeScript glue commands
if command -v pnpm >/dev/null 2>&1; then
  info "Installing workspace deps + building scripts"
  (
    cd "$REPO_ROOT" || exit
    pnpm install --frozen-lockfile >/dev/null 2>&1 || pnpm install >/dev/null 2>&1
  )
  (
    cd "$DIR/scripts" || exit
    pnpm run build >/dev/null 2>&1
  )
  # Install lefthook git hooks (check on commit, test on push).
  if [[ -d "$REPO_ROOT/.git" ]]; then
    if ( cd "$REPO_ROOT" || exit; pnpm exec lefthook install >/dev/null 2>&1 ); then
      ok "Git hooks installed (lefthook: check on commit, test on push)"
    fi
  fi
fi

mkdir -p "$BIN_DIR"
info "Installing commands into $BIN_DIR"

# Stream Deck launches keys from launchd, whose PATH is only
# /usr/bin:/bin:/usr/sbin:/sbin — no nvm, no homebrew. A `#!/usr/bin/env node`
# shebang there dies with "env: node: No such file or directory", so instead of
# symlinking the scripts we write a wrapper per command with the interpreter
# pinned, falling back to a PATH lookup if that node is ever removed.
NODE_BIN="$(command -v node 2>/dev/null || true)"
[[ -n "$NODE_BIN" ]] || warn "node not found on PATH — the wrappers will rely on a runtime lookup"

shopt -s nullglob
linked=0
for f in "$DIR"/scripts/bin/*.js; do
  base="$(basename "$f" .js)"
  # Skip tsdown shared chunks (hashed names like ctx-XXXX.js); install only the
  # command entrypoints. Node resolves the sibling chunks via the real path.
  case "$base" in
    switch-claude-account|summon-agent|summon-claude|focus-mode|meeting-mode|quick-capture|standup|slack-status)
      target="$BIN_DIR/sd-${base}"
      # Must unlink first: a previous install left a symlink here, and `cat >`
      # would write straight through it into the built script.
      rm -f "$target"
      cat > "$target" <<WRAPPER
#!/bin/sh
# Generated by streamdeck/install.sh — do not edit; re-run install.sh instead.
NODE="${NODE_BIN}"
[ -x "\$NODE" ] || NODE="\$(command -v node 2>/dev/null)"
exec "\$NODE" "${f}" "\$@"
WRAPPER
      chmod +x "$target"
      ok "sd-${base} -> $f"
      linked=1
      ;;
  esac
done
[[ "$linked" == 1 ]] || warn "No built commands found — run: pnpm -C \"$DIR/scripts\" run build"
case ":$PATH:" in
  *":$BIN_DIR:"*) : ;;
  *) warn "$BIN_DIR is not on your PATH — add it in your shell rc" ;;
esac

# 4. Secrets template
mkdir -p "$CFG_DIR"
if [[ ! -f "$SECRETS" ]]; then
  cat > "$SECRETS" <<'EOF'
# Stream Deck secrets — DO NOT COMMIT. Chmod 600.
# Optional: the plugins fall back to `gh auth token` when this is blank.
GITHUB_TOKEN=
# Only needed by weekly-metrics' `commits` metric (commit search has no @me).
GITHUB_LOGIN=
SLACK_TOKEN=
WAKATIME_API_KEY=
JIRA_BASE_URL=
JIRA_EMAIL=
JIRA_API_TOKEN=
# Optional: the calendar keys read the local macOS Calendar by default.
# Set this only to use an .ics feed instead.
ICAL_URL=
# Optional preferences
STREAMDECK_TERMINAL=terminal        # terminal|iterm|wezterm|kitty
STREAMDECK_DEFAULT_REPO=$HOME/code
STREAMDECK_INBOX=$HOME/inbox.md
STREAMDECK_FOCUS_PLAYLIST=          # spotify: URI
EOF
  chmod 600 "$SECRETS"
  ok "Created secrets template: $SECRETS (fill it in)"
else
  ok "Secrets file already exists: $SECRETS"
fi

# 5. Custom plugins: build and link them into the Stream Deck app
PLUGINS_DIR="$HOME/Library/Application Support/com.elgato.StreamDeck/Plugins"
if command -v pnpm >/dev/null 2>&1 && [[ -d "$PLUGINS_DIR" ]]; then
  info "Building + linking the custom plugins"
  # Don't swallow build output: a failure here would otherwise leave the
  # previous artifact linked with no hint as to why nothing changed.
  ( cd "$REPO_ROOT" && pnpm run build ) || exit 1
  ( cd "$DIR/icons" && pnpm run build ) || exit 1
  for src in "$DIR"/plugins/*/*.sdPlugin; do
    [[ -d "$src" ]] || continue
    dest="$PLUGINS_DIR/$(basename "$src")"
    # `ln -sfn` replaces a symlink but *not* a real directory — it would create
    # the link _inside_ it and Stream Deck would keep loading the stale copy.
    rm -rf "$dest"
    ln -s "$src" "$dest"
    ok "$(basename "$src") linked"
  done
fi

# 6. Plugin checklist (the ones we can't install for you)
echo
info "Install these from their releases (see streamdeck/plugins/README.md)"
cat <<'EOF'
  [ ] AgentDeck                 npx @agentdeck/setup && agentdeck daemon install
  [ ] stream-deck-ai-limits     github.com/lenadweb/stream-deck-ai-limits
  [ ] stream-deck-ical          github.com/pedrofuentes/stream-deck-ical
  [ ] essentials-for-spotify    github.com/ntanis-dev/essentials-for-spotify
  [ ] streamdeck-jira           github.com/mediabounds/streamdeck-jira
EOF
echo
info "Then write the 3-page profile onto the deck:"
cat <<'EOF'
  osascript -e 'tell application "Elgato Stream Deck" to quit'
  pnpm -C streamdeck/profiles apply
  open -a "Elgato Stream Deck"
EOF
echo
ok "Bootstrap complete."
